### ISSUE TITLE
Publish datasets as torrent files

### ISSUE THREAD

**Issue by wizzard0** [cvondrick/videogan#1]
The article says there's 7 TB of files, they could be published as a set of torrent files that could be community-seeded from different machines.

It makes sense to split them to amounts individually downloadable to a typical machine (e.g. 7 torrents for 1 tb each)

**Comment by cvondrick** [comment]
Hi! Yes, we are planning on doing that. We have been tarballing the dataset into several chunks, and MIT should be able to host it soon. But, it would be great if others can mirror it.

**Comment by cvondrick** [comment]
We have released the first version of the dataset here: http://web.mit.edu/vondrick/tinyvideo/#data
