### ISSUE TITLE
PyTorch version of code

### ISSUE THREAD

**Issue by prannayk** [cvondrick/videogan#5]
Is there a PyTorch version of the code or do the authors of the paper wish to release it? 

It might be helpful to use it.

**Comment by cvondrick** [comment]
If someone wants to implement a PyTorch version, that would be great! We don't have one off-hand.

**Comment by GV1028** [comment]
Hey! I implemented a tensorflow version of the paper. You can check it out here: https://github.com/GV1028/videogan
