### ISSUE TITLE
Issues running main.lua

### ISSUE THREAD

**Issue by cryptedp** [cvondrick/videogan#6]
Hi

When I try to run main.lua I get this error message : 

/data/vision/torralba/crossmodal/flickr_videos/scene_extract/lists-full/_b_beach.txt.train : No such file or directory

Do I have to manually download all the txt file of your project or is there a lua script in the project, which downloads all the data ?

**Comment by cvondrick** [comment]
You'll have to download each file you need. Sorry! There isn't too many though.

**Comment by cryptedp** [comment]
Okay but I also need to download the videos right ?

**Comment by gsygsy96** [comment]
Could you tell me where to download this files? @cryptedp @cvondrick

**Comment by cryptedp** [comment]
You can download the golf files by using wget like this : wget http://data.csail.mit.edu/videogan/beach.tar.bz2 @shanYanGuan

**Comment by gsygsy96** [comment]
Thanks!!!But it is too large. I just want see the structure of _b_beach.txt.train. Could you send it to my email? Thanks again! My email is shyanguan@gmail.com @cryptedp
